# vim: nospell
# .travis.yml

sudo: false

language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

# fail CI build using rustfmt in diff mode
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test

after_success:
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install cargo-benchcmp --force; # not using --force will fail if it's already on the system
        cargo bench > benches-variable;
        git fetch;
        git checkout master;
        cargo bench > benches-control;
        cargo benchcmp benches-control benches-variable;
    fi

